import type { Metadata } from "next";
import Template from "@/components/template";
import "./globals.css";

export const metadata: Metadata = {
  title: "Tailgate Warriors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Template>{children}</Template>
      </body>
    </html>
  );
}
